<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $workshop  = Category::where('slug', 'workshop')->first();
        $seminar   = Category::where('slug', 'seminar')->first();
        $pelatihan = Category::where('slug', 'pelatihan')->first();

        Activity::query()->insert([
            [
                'category_id' => $workshop->id,
                'code' => 'WS-001',
                'title' => 'Workshop Git Dasar',
                'description' => 'Latihan kolaborasi repository.',
                'start_at' => '2026-10-05',
                'end_at' => '2026-10-05',
                'capacity' => 30,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminar->id,
                'code' => 'SM-001',
                'title' => 'Seminar Web Quality',
                'description' => 'Pengenalan maintainability dan testing.',
                'start_at' => '2026-10-12',
                'end_at' => '2026-10-12',
                'capacity' => 100,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshop->id,
                'code' => 'WS-002',
                'title' => 'Workshop Laravel CRUD',
                'description' => 'Membuat kerangka CRUD Laravel.',
                'start_at' => '2026-10-15',
                'end_at' => '2026-10-16',
                'capacity' => 25,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $pelatihan->id,
                'code' => 'PL-001',
                'title' => 'Pelatihan Database Design',
                'description' => 'Membuat desain database yang baik.',
                'start_at' => '2026-10-01',
                'end_at' => '2026-10-02',
                'capacity' => 20,
                'status' => 'completed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminar->id,
                'code' => 'SM-002',
                'title' => 'Seminar Keamanan Siber',
                'description' => 'Pengenalan dasar keamanan siber.',
                'start_at' => '2026-10-08',
                'end_at' => '2026-10-08',
                'capacity' => 150,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshop->id,
                'code' => 'WS-003',
                'title' => 'Workshop Docker Basics',
                'description' => 'Memahami containerization dengan Docker.',
                'start_at' => '2026-10-20',
                'end_at' => '2026-10-21',
                'capacity' => 20,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $pelatihan->id,
                'code' => 'PL-002',
                'title' => 'Pelatihan API Development',
                'description' => 'Membuat REST API dengan Laravel.',
                'start_at' => '2026-10-22',
                'end_at' => '2026-10-23',
                'capacity' => 25,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminar->id,
                'code' => 'SM-003',
                'title' => 'Seminar Cloud Computing',
                'description' => 'Pengenalan layanan cloud.',
                'start_at' => '2026-10-25',
                'end_at' => '2026-10-25',
                'capacity' => 200,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshop->id,
                'code' => 'WS-004',
                'title' => 'Workshop UI/UX Design',
                'description' => 'Desain antarmuka yang user-friendly.',
                'start_at' => '2026-10-28',
                'end_at' => '2026-10-29',
                'capacity' => 30,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $pelatihan->id,
                'code' => 'PL-003',
                'title' => 'Pelatihan Testing Laravel',
                'description' => 'Unit testing dan feature testing.',
                'start_at' => '2026-10-30',
                'end_at' => '2026-10-31',
                'capacity' => 20,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminar->id,
                'code' => 'SM-004',
                'title' => 'Seminar Machine Learning Intro',
                'description' => 'Pengenalan dasar machine learning.',
                'start_at' => '2026-11-01',
                'end_at' => '2026-11-01',
                'capacity' => 120,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshop->id,
                'code' => 'WS-005',
                'title' => 'Workshop DevOps Pipeline',
                'description' => 'Membangun CI/CD pipeline.',
                'start_at' => '2026-11-03',
                'end_at' => '2026-11-04',
                'capacity' => 20,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $pelatihan->id,
                'code' => 'PL-004',
                'title' => 'Pelatihan Agile Scrum',
                'description' => 'Metodologi Agile untuk tim pengembang.',
                'start_at' => '2026-11-05',
                'end_at' => '2026-11-06',
                'capacity' => 35,
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $seminar->id,
                'code' => 'SM-005',
                'title' => 'Seminar Open Source',
                'description' => 'Kontribusi ke proyek open source.',
                'start_at' => '2026-11-08',
                'end_at' => '2026-11-08',
                'capacity' => 80,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $workshop->id,
                'code' => 'WS-006',
                'title' => 'Workshop Mobile Development',
                'description' => 'Pembuatan aplikasi mobile dengan Flutter.',
                'start_at' => '2026-11-10',
                'end_at' => '2026-11-12',
                'capacity' => 25,
                'status' => 'published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
